/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.88
 * Generated at: 2020-01-19 03:55:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<link href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" \n");
      out.write("\trel=\"stylesheet\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" \n");
      out.write("\tcrossorigin=\"anonymous\"/>\n");
      out.write("<meta charset=\"ISO-8859-1\">\n");
      out.write("<title>Bienvenido a Maria Parado De Bellido</title>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"jss/Js_index.js\"></script>\n");
      out.write("\n");
      out.write("<body style=\"background-image: url('img/222.jpg'); background-size: 100%;\" onload=\"fc_alerta(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(")\">\n");
      out.write("\n");
      out.write("\t\n");
      out.write("\t<div class=\"card bg-primary text-dark\" \n");
      out.write("             style=\"background-color: rgba(255, 255,255, 0.4) !important;\">\n");
      out.write("\t<h2>Portal \"Maria Parado de Bellido\" </h2></div>\n");
      out.write("\n");
      out.write("\t\t\n");
      out.write(" <form action=\"ingresar\" method=\"get\">    \n");
      out.write("\t<div class=\"card text-dark bg-danger mb-3\" style=\"background-color: rgba(255, 255,255, 0.4) !important;\n");
      out.write("                position: absolute; right: 100px; top: 250px\">\n");
      out.write("\t\t<table>\n");
      out.write("\t\t\t<tr><td><h3>Iniciar sesion</h3></td></tr>\n");
      out.write("        \t<tr><td><strong>Usuario:</strong></td>\n");
      out.write("            <td><input type=\"text\" name=\"txtUsu\" placeholder=\"Usuario\"/></td></tr>\n");
      out.write("            <tr><td><strong>Contraseña:</strong></td>\n");
      out.write("            <td><input type=\"password\" name=\"txtPas\" placeholder=\"****\"/></td></tr>\n");
      out.write("            <tr><td colspan=\"2\" align=\"right\"><input type=\"submit\" name=\"btnAcc\" value=\"ACCEDER\"  \n");
      out.write("                    class=\"btn btn-warning btn-block\"></td></tr>\n");
      out.write("            <tr><td colspan=\"2\" class=\"text-dark text-right\">¿No eres alumno? \n");
      out.write("            <a href=\"Matricular.jsp\">\n");
      out.write("            ¡matriculate aquí!</a><td></tr>\n");
      out.write("        </table>\n");
      out.write("</div>\n");
      out.write("</form>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
